simulate_strike:
  name: Simulate Lightning Strike
  description: Simulate a lightning strike event to test map geolocation entities and dashboard 3D visualization.
  fields:
    latitude:
      name: Latitude
      description: The latitude coordinate where the simulated strike occurred. If left blank, a random coordinate close to the home configuration is generated.
      required: false
      example: 40.1234
      selector:
        number:
          min: -90
          max: 90
          step: any
          mode: box
    longitude:
      name: Longitude
      description: The longitude coordinate where the simulated strike occurred. If left blank, a random coordinate close to the home configuration is generated.
      required: false
      example: -75.1234
      selector:
        number:
          min: -180
          max: 180
          step: any
          mode: box
